name: Main
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        id: test
        uses: moorara/actions/go-cover@main
        with:
          codeclimate_reporter_id: ${{ secrets.CODECLIMATE_REPORTER_ID }}
      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ${{ steps.test.outputs.coverage_report_file }}
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: moorara/actions/semver@main
      - name: Build Image
        run: make docker docker_tag=$(cat .semver)
      - name: Push Image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
          make push docker_tag=$(cat .semver)
